[metadata.heroku]
  root-package = "github.com/kivutar/smart-contract-graphql"
  go-version = "1.10"
  install = [ "./..." ]

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.13"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"
